### ISSUE TITLE
Error while integrating xposed source code via local manifest

### ISSUE THREAD

**Issue by hahaopsmeow** [romracer/XposedTools#4]
So, I did everything according to the instruction and I got:

```
Fetching project rovo89/android_art
error: Cannot fetch rovo89/android_art (GitError: --force-sync not enabled; cannot overwrite a local work tree. If you're comfortable with the possibility of losing the work tree's git metadata, use `repo sync --force-sync art` to proceed.)
Fetching project platform/external/icu
Exception in thread Thread-211:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/max/xposed/android-6.0.1_r45/.repo/repo/subcmds/sync.py", line 270, in _FetchProjectList
    success = self._FetchHelper(opt, project, *args, **kwargs)
  File "/home/max/xposed/android-6.0.1_r45/.repo/repo/subcmds/sync.py", line 314, in _FetchHelper
    prune=opt.prune)
  File "/home/max/xposed/android-6.0.1_r45/.repo/repo/project.py", line 1148, in Sync_NetworkHalf
    self._InitGitDir(force_sync=force_sync)
  File "/home/max/xposed/android-6.0.1_r45/.repo/repo/project.py", line 2177, in _InitGitDir
    raise e
GitError: --force-sync not enabled; cannot overwrite a local work tree. If you're comfortable with the possibility of losing the work tree's git metadata, use `repo sync --force-sync art` to proceed.

Fetching projects:  46% (210/456)
```

The problem is that git cannot clone `rovo89/android_art`into `art` folder because it already exists.

Should I remove original `art`?

**Comment by romracer** [comment]
You'll need to remove the stock art.  The local manifest should do this.  I believe there are some example local manifests in the repo but they probably aren't fully up to date.  Here's the marshmallow one I used for version 86.0:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <remote name="github" fetch="https://github.com" />
  <project path="external/busybox" name="romracer/android_external_busybox" remote="github" revision="xposed"/>
  <project path="external/mkbootimg" name="romracer/android_external_mkbootimg" remote="github" revision="master"/>
  <project path="frameworks/base/cmds/xposed" name="romracer/Xposed" remote="github" revision="systemless"/>
  <remove-project name="platform/art" />
  <project path="art" name="rovo89/android_art" remote="github" revision="xposed-marshmallow"/>
</manifest>
```

**Comment by hahaopsmeow** [comment]
@romracer thank you a lot! I already did compile xposed with local import.
